<script lang="ts">
	import { scale } from 'svelte/transition';
	export let event: EventData;
	let pointsColor = event.p < 0 ? 'text-red-500' : event.p > 0 ? 'text-green-500' : 'text-gray-500';
	const map: Map<Number, String> = new Map<Number, String>([
		[0, 'Unknown'],
		[1, 'Schuss aufs Tor'],
		[2, 'Bonus: Zweikampf als letzter Mann'],
		[4, 'Ballbesitz nach geblockter Flanke'],
		[5, 'Geklärt'],
		[6, 'Ballgewinn'],
		[7, 'Flanke geblockt'],
		[9, 'Ausgespielt worden'],
		[10, 'Fehler vor Torschuss'],
		[11, 'Elfmeter verschuldet'],
		[101, 'Tor (ABW)'],
		[102, 'Tor (MF)'],
		[103, 'Tor (ANG)'],
		[104, 'Tor (Einwechselspieler)'],
		[105, 'Elfmeter verwandelt'],
		[107, 'Elfmeter rausgeholt'],
		[110, 'Großchance kreiert'],
		[112, 'Torschussvorlage'],
		[113, 'Erfolgreiche Flanke'],
		[115, 'Gegner ausgedribbelt'],
		[116, 'Pass vorderes Drittel'],
		[117, 'Pass gegnerische Hälfte'],
		[118, 'Abseits'],
		[119, 'Großchance vergeben'],
		[122, 'Elfmeter verschossen'],
		[202, 'Minutenbonus'],
		[203, 'Ballverlust'],
		[207, 'Foul'],
		[208, 'Gelbe Karte'],
		[300, 'Zu null gespielt (TW)'],
		[301, 'Zu null gespielt (ABW)'],
		[302, 'Zu null gespielt (MF)'],
		[303, 'Spiel gewonnen'],
		[304, 'Teamtor'],
		[309, 'Tor kassiert'],
		[315, 'Zu null gespielt (ANG)'],
		[403, 'Erfolgreiches Rauslaufen (TW)'],
		[404, 'Faustabwehr (TW)'],
		[405, 'Flanke abgefangen (TW)'],
		[500, 'Startelf'],
		[501, 'Torvorlage (ABW)'],
		[503, 'Torvorlage (MF)'],
		[504, 'Torvorlage (ANG)'],
		[508, 'Spiel verloren'],
		[513, 'Tor eingeleitet (ABW)'],
		[601, 'Ausgewechselt'],
		[602, 'Eingewechselt'],
		[800, 'Anpfiff'],
		[801, 'Halbzeit'],
		[803, 'Abpfiff'],
		[802, 'Anpfiff zweite Halbzeit'],
		[1007, 'Erfolgreicher Abwurf (TW)'],
		[1010, 'Präziser langer Pass'],
		[1013, 'Pass des Todes'],
		[1015, 'Luftzweikampf verloren'],
		[1016, 'Luftzweikampf gewonnen'],
		[1065, 'Bonus: Fernschusstor'],
		[1083, 'Lattenkracher'],
		[1085, 'Pfostentreffer'],
		[1114, 'Ball gefangen (TW)'],
		[1115, 'Parade'],
		[1125, 'Uff! Falscher Einwurf'],
		[1126, '<Leer>'],
		[1130, 'Bonus: Absichtliche Vorlage'],
		[1142, 'Handspiel'],
		[1146, 'Pass gestört'],
		[1147, 'Gegner gestört'],
		[1164, 'Ball zu weit vorgelegt'],
		[1178, 'Schuss gehalten (TW)'],
		[1179, 'Fernschuss gehalten (TW)'],
		[1188, 'Ball im Stand abgewehrt (TW)'],
		[1214, 'Zweikampf geführt'],
		[1220, 'Schlechte Ballkontrolle'],
		[1222, 'Ecke rausgeholt'],
		[1223, 'Gewonnener Zweikampf'],
		[1230, 'Eigentor erzwungen'],
		[1300, 'Position Torwart'],
		[1301, 'Position Abwehr'],
		[1302, 'Position Mittelfeld'],
		[1303, 'Position Angriff'],
		[1402, 'Bonus: Glanzparade'],
		[1403, 'Schuss aufs Tor'],
		[1404, 'Schuss knapp am Tor vorbei'],
		[1405, 'Schuss weit am Tor vorbei'],
		[1406, 'Geblockter Torschuss']
	]);
</script>

<div transition:scale class="grid grid-cols-6 w-full text-left items-center">
	<p>{event.ts}'</p>
	<p class="col-span-4">{map.get(event.e)}</p>
	<p class="text-right {event.p > 15 ? 'font-extrabold' : ''} {pointsColor}">
		{event.p <= 0 ? event.p : '+' + event.p}
	</p>
</div>
